# Generated by Django 2.0.5 on 2018-05-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministry',
            options={'verbose_name_plural': 'ministries'},
        ),
    ]
