# Generated by Django 2.0.5 on 2018-06-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0002_auto_20180529_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
