# Generated by Django 2.0.5 on 2018-06-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180610_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags1',
            new_name='tags',
        ),
    ]
