# Generated by Django 2.0.5 on 2018-05-29 18:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('name_pl', models.CharField(max_length=128, null=True)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('summary', models.CharField(max_length=256)),
                ('summary_pl', models.CharField(max_length=256, null=True)),
                ('summary_en', models.CharField(max_length=256, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('content_pl', ckeditor.fields.RichTextField(null=True)),
                ('content_en', ckeditor.fields.RichTextField(null=True)),
                ('image', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'projects',
            },
        ),
    ]
